### ISSUE TITLE
Wrong CPU percent

### ISSUE THREAD

**Issue by bantomak17** [Napsty/check_lxc#7]
Hi 
Host PC have 8 cpus. so i set cpu number 2 in container.  
lxc-cgroup -n name cpuset.cpus 2

and i made cpu load 100 % in container. comand is below.
dd if=/dev/zero of=/dev/null

and run the check_lxc.
./check_lxc.sh -n name -t cpu 
but result is CPU Usage: 52%.

I think the result should be 100 %..

**Comment by Napsty** [comment]
Read the info on the documentation page: https://www.claudiokuenzler.com/monitoring-plugins/check_lxc.php

> Important note on cpu check: It is important to understand what the cpu check does. It will not tell you the usage of the CPU itself. Instead the number of jiffies (time spent on CPU) of a container is compared to the total number of jiffies of the host during a given period (default 5s, can be modified with -s parameter). This means the plugin's cpu check will tell you how much a container can be accounted for of the current cpu usage. This is not bullet proof, but it helps to find the most busy containers.

So this can result in more than 100% because it spent more time on cpu than the host itself. It's not a CPU usage as you would expect, I know. 

As of now I'm not aware of any other possibility to check the usage of a container compared to the full host. I even briefly spoke with Stéphane Graber at the Open Source Summit 2017 about it if he has a better idea.
